package hooks

import (
	"cmp"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/moukrea/automodel/internal/catalog"
	"github.com/moukrea/automodel/internal/jev"
	"github.com/moukrea/automodel/internal/ledger"
	"github.com/moukrea/automodel/internal/router"
	"github.com/moukrea/automodel/internal/state"
)

const workGoal = "Find why checkouts hand the same connection to two workers under load, and fix it"

// workSession sets up a warm session whose decision in force is tier and
// mode, and whose work in progress is work (at mode).
func workSession(t *testing.T, env *router.Env, sid, tier, mode, work string) {
	t.Helper()
	warmSession(t, env, sid, tier, 300_000)
	c := env.Catalog
	_, effort, wf := c.Resolve(c.Tier(catalog.ScopeMain, tier), mode)
	env.State.Update(sid, func(s *state.Session) bool {
		s.Main.Effort, s.Main.Mode, s.Main.Workflows = effort, mode, wf
		s.UltracodeOn, s.UltracodeEpoch = wf, s.Main.Epoch
		s.Work = &state.Work{Tier: work, Mode: mode, Goal: workGoal, Since: time.Now().Add(-time.Hour)}
		return true
	})
}

// busyTranscript is a turn still running: the last message called a tool
// and no turn end followed.
func busyTranscript(t *testing.T) string {
	p := filepath.Join(t.TempDir(), "busy.jsonl")
	os.WriteFile(p, []byte(strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"Add the price column to the CSV export"}}`,
		`{"type":"assistant","message":{"role":"assistant","stop_reason":"tool_use","content":[{"type":"tool_use","id":"t1","name":"Edit","input":{}}]}}`,
		`{"type":"user","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"t1","content":"ok"}]}}`,
	}, "\n")+"\n"), 0o600)
	return p
}

// startedTranscript is a turn that just started: its prompt is written,
// none of the turn's own entries yet (Claude Code writes them in batches).
func startedTranscript(t *testing.T) string {
	p := filepath.Join(t.TempDir(), "started.jsonl")
	os.WriteFile(p, []byte(strings.Join([]string{
		`{"type":"assistant","message":{"role":"assistant","stop_reason":"end_turn","content":[{"type":"text","text":"The race is in the pool's checkout path."}]}}`,
		`{"type":"system","subtype":"turn_duration"}`,
		`{"type":"user","message":{"role":"user","content":"Add the price column to the CSV export"}}`,
	}, "\n")+"\n"), 0o600)
	return p
}

// shellTranscript is a turn that ended, then a shell command run with "!"
// (Claude Code's bash mode: a caveat, its input, its output), and no
// assistant entry after it.
func shellTranscript(t *testing.T) string {
	p := filepath.Join(t.TempDir(), "shell.jsonl")
	os.WriteFile(p, []byte(strings.Join([]string{
		`{"type":"user","message":{"role":"user","content":"Find why checkouts hand the same connection to two workers under load, and fix it"}}`,
		`{"type":"assistant","message":{"role":"assistant","stop_reason":"end_turn","content":[{"type":"text","text":"Fixed: the pool now leases under the lock. Tests pass."}]}}`,
		`{"type":"system","subtype":"stop_hook_summary"}`,
		`{"type":"user","isMeta":true,"message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"}}`,
		`{"type":"user","message":{"role":"user","content":"<bash-input>git status</bash-input>"}}`,
		`{"type":"user","message":{"role":"user","content":"<bash-stdout>On branch main\nnothing to commit</bash-stdout><bash-stderr></bash-stderr>"}}`,
	}, "\n")+"\n"), 0o600)
	return p
}

// The work in progress (router.Judge): a follow-up keeps at least its tier
// and mode, separate work gets its own level, requests in words win, and a
// prompt typed mid-turn or sent by another session never lowers anything.
func TestWorkInProgress(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	busy, started, shell := busyTranscript(t), startedTranscript(t), shellTranscript(t)
	x := func(kv ...any) map[string]float64 {
		m := map[string]float64{}
		for i := 0; i < len(kv); i += 2 {
			m[kv[i].(string)] = kv[i+1].(float64)
		}
		return m
	}
	for i, c := range []struct {
		name       string
		tier, mode string // the decision in force, and the work in progress's mode
		work       string // the work in progress's tier ("": the decision's)
		transcript string
		prompt     string
		jev        fa
		ask        string // an explicit-request question the prompt must carry
		// The decision, and the work in progress after the prompt (newGoal:
		// the prompt started it).
		want, wantMode         string
		wantWork, wantWorkMode string
		newGoal                bool
	}{
		{name: "an extension at xhigh stays at xhigh", tier: "xhigh", prompt: "also add a regression test for that interleaving",
			jev: fa{tier: "medium", conf: 0.85, rel: "extend", relP: 0.97}, want: "xhigh", wantWork: "xhigh"},
		{name: "a side question holds", tier: "xhigh", prompt: "is CI green yet?",
			jev: fa{tier: "low", conf: 0.95, rel: "side_question"}, want: "xhigh", wantWork: "xhigh"},
		{name: "a harder extension raises the work", tier: "medium", prompt: "and handle the retry storm when the pool is exhausted too",
			jev: fa{tier: "xhigh", conf: 0.8, rel: "extend"}, want: "xhigh", wantWork: "xhigh"},
		{name: "a wrap-up lowers, the work stays", tier: "xhigh", prompt: "write the commit message",
			jev: fa{tier: "low", conf: 0.95, rel: "wrap_up"}, want: "low", wantWork: "xhigh"},
		{name: "a new task lowers and starts new work", tier: "xhigh", prompt: "now rename the config loader to settings",
			jev: fa{tier: "low", conf: 0.9, rel: "new_task"}, want: "low", wantWork: "low", newGoal: true},
		{name: "a hard new task on a low session goes up", tier: "low", prompt: "Next: find why refunds are counted twice under load",
			jev: fa{tier: "xhigh", conf: 0.9, rel: "new_task"}, want: "xhigh", wantWork: "xhigh", newGoal: true},
		{name: "unsure between follow-up and separate: holds", tier: "high", prompt: "et le cas où le worker meurt ?",
			jev: fa{tier: "low", conf: 0.9, rel: "new_task", relP: 0.2}, want: "high", wantWork: "high"}, // new_task + wrap_up + aside 0.47
		{name: "an effort asked in words raises", tier: "high", prompt: "fais la suite en xhigh", ask: "explicit_effort_xhigh",
			jev: fa{tier: "high", conf: 0.9, rel: "extend", x: x("effort_xhigh", 0.95)}, want: "xhigh", wantWork: "xhigh"},
		{name: "a mention of an effort doesn't", tier: "high", prompt: "pourquoi c'est resté en xhigh tout à l'heure ?", ask: "explicit_effort_xhigh",
			jev: fa{tier: "low", conf: 0.9, rel: "side_question", x: x("effort_xhigh", 0.04)}, want: "high", wantWork: "high"},
		{name: "passe en low lowers the work too", tier: "xhigh", prompt: "passe en low pour la suite, c'est mécanique", ask: "explicit_effort_low",
			jev: fa{tier: "medium", conf: 0.9, rel: "extend", x: x("effort_low", 0.93)}, want: "low", wantWork: "low"},
		// More thinking is one rank above what runs: on a follow-up Jev's
		// level rates the words asking for it (held-out run 1: low work,
		// "think harder" read as xhigh), on new work it is a floor.
		{name: "think harder on low work: medium", tier: "low", prompt: "explain the touch chain again but think harder: why would a price change not refresh the card?", ask: "explicit_effort_more",
			jev: fa{tier: "xhigh", conf: 0.4, rel: "extend", x: x("effort_more", 0.97)}, want: "medium", wantWork: "medium"},
		{name: "think harder on xhigh work: max", tier: "xhigh", prompt: "think harder, the last two fixes for this hang didn't hold", ask: "explicit_effort_more",
			jev: fa{tier: "xhigh", conf: 0.9, rel: "continue", x: x("effort_more", 0.95)}, want: "max", wantWork: "max"},
		{name: "think harder on a go-ahead: one rank up, whatever the level", tier: "low", prompt: "ok, go on, but think harder this time", ask: "explicit_effort_more",
			jev: fa{tier: "xhigh", conf: 0.9, rel: "continue", x: x("effort_more", 0.95)}, want: "medium", wantWork: "medium"},
		// An extension adds work: when Jev is sure its level is higher,
		// asking for more thinking doesn't get less than the same prompt
		// without the words.
		{name: "think harder on an extension rated xhigh: xhigh", tier: "medium", prompt: "think harder on this one: also retry the idempotent calls when the pool is exhausted", ask: "explicit_effort_more",
			jev: fa{tier: "xhigh", conf: 0.9, rel: "extend", relP: 0.95, x: x("effort_more", 0.95)}, want: "xhigh", wantWork: "xhigh"},
		{name: "think harder on an extension rated max: max", tier: "medium", prompt: "think harder on this one: also redesign the lock ordering across the scheduler, the pool and the queue", ask: "explicit_effort_more",
			jev: fa{tier: "max", conf: 0.9, rel: "extend", x: x("effort_more", 0.95)}, want: "max", wantWork: "max"},
		{name: "think harder on a new task: a floor above the session", tier: "medium", prompt: "next: design how to shard the job queue, and think hard about it", ask: "explicit_effort_more",
			jev: fa{tier: "xhigh", conf: 0.9, rel: "new_task", x: x("effort_more", 0.95)}, want: "xhigh", wantWork: "xhigh", newGoal: true},
		{name: "ultrathink: xhigh at least, without a question", tier: "low", prompt: "ultrathink: and check the other places we read the lease without the lock",
			jev: fa{tier: "low", conf: 0.9, rel: "extend"}, want: "xhigh", wantWork: "xhigh"},
		// A wrap-up, a side question or an aside is answered for that turn:
		// what it needs raises that answer only.
		{name: "ultrathink on a side question: that answer only", tier: "low", prompt: "ultrathink: are there other places we read the lease without the lock?",
			jev: fa{tier: "low", conf: 0.9, rel: "side_question"}, want: "xhigh", wantWork: "low"},
		{name: "a side question rated above the work: that answer only", tier: "medium", prompt: "why can't the scheduler deadlock with the new lock order? walk me through it",
			jev: fa{tier: "xhigh", conf: 0.9, rel: "side_question"}, want: "xhigh", wantWork: "medium"},
		{name: "ultracode asked on a continuing turn turns it on", tier: "high", prompt: "continue, en ultracode cette fois", ask: "explicit_mode_ultracode",
			jev: fa{tier: "high", conf: 0.9, ultra: 0.3, rel: "continue", x: x("mode_ultracode", 0.95)}, want: "xhigh", wantMode: "ultracode", wantWork: "xhigh", wantWorkMode: "ultracode"},
		{name: "pas besoin d'ultracode turns it off", tier: "xhigh", mode: "ultracode", prompt: "pas besoin d'ultracode, corrige juste le message d'erreur", ask: "explicit_mode_off",
			jev: fa{tier: "low", conf: 0.9, ultra: 0.1, rel: "extend", x: x("mode_off", 0.9)}, want: "xhigh", wantWork: "xhigh"},
		{name: "a follow-up keeps the mode on", tier: "xhigh", mode: "ultracode", prompt: "et vérifie aussi le module de facturation",
			jev: fa{tier: "medium", conf: 0.9, ultra: 0.05, rel: "extend"}, want: "xhigh", wantMode: "ultracode", wantWork: "xhigh", wantWorkMode: "ultracode"},
		{name: "a small new task in an ultracode session gets no mode", tier: "xhigh", mode: "ultracode", prompt: "now write the migration notes for ops",
			jev: fa{tier: "low", conf: 0.9, ultra: 0.4, rel: "new_task"}, want: "low", wantWork: "low", newGoal: true},
		// A wrap-up, a side question or an aside runs without the work's
		// mode, whatever Jev's mode answer (it reads the whole work: 0.92 to
		// 0.95 on these, held-out run 1); the work keeps it.
		{name: "a wrap-up in an ultracode session runs alone", tier: "xhigh", mode: "ultracode", prompt: "commit wave 2, one commit per service",
			jev: fa{tier: "low", conf: 0.9, ultra: 0.93, rel: "wrap_up", relP: 0.78}, want: "low", wantWork: "xhigh", wantWorkMode: "ultracode"},
		{name: "an aside in an ultracode session runs alone", tier: "xhigh", mode: "ultracode", prompt: "small unrelated question: what's the Python equivalent of flatMap?",
			jev: fa{tier: "low", conf: 0.9, ultra: 0.95, rel: "aside"}, want: "low", wantWork: "xhigh", wantWorkMode: "ultracode"},
		{name: "a side question holds the tier, not the mode", tier: "xhigh", mode: "ultracode", prompt: "how many handlers are left?",
			jev: fa{tier: "low", conf: 0.9, ultra: 0.92, rel: "side_question"}, want: "xhigh", wantWork: "xhigh", wantWorkMode: "ultracode"},
		{name: "a side question typed mid-turn keeps the turn's mode", tier: "xhigh", mode: "ultracode", transcript: busy, prompt: "how many handlers are left?",
			jev: fa{tier: "low", conf: 0.9, ultra: 0.1, rel: "side_question"}, want: "xhigh", wantMode: "ultracode", wantWork: "xhigh", wantWorkMode: "ultracode"},
		{name: "ultracode asked for a side question: that answer only", tier: "high", prompt: "answer this one with ultracode: which handlers skip the auth check?", ask: "explicit_mode_ultracode",
			jev: fa{tier: "medium", conf: 0.9, ultra: 0.2, rel: "side_question", x: x("mode_ultracode", 0.95)}, want: "xhigh", wantMode: "ultracode", wantWork: "high"},
		{name: "a prompt typed mid-turn never lowers", tier: "high", transcript: busy, prompt: "ah et les prix en euros TTC",
			jev: fa{tier: "low", conf: 0.98, rel: "new_task"}, want: "high", wantWork: "high"},
		{name: "typed before the turn's first entries: mid-turn", tier: "high", transcript: started, prompt: "au fait, garde les messages d'erreur en anglais",
			jev: fa{tier: "low", conf: 0.98, rel: "new_task"}, want: "high", wantWork: "high"},
		{name: "the prompt's own turn is not mid-turn", tier: "high", transcript: started, prompt: "Add the price column to the CSV export",
			jev: fa{tier: "low", conf: 0.98, rel: "new_task"}, want: "low", wantWork: "low", newGoal: true},
		{name: "after a shell command: not mid-turn", tier: "xhigh", transcript: shell, prompt: "now rename the config loader to settings",
			jev: fa{tier: "low", conf: 0.9, rel: "new_task"}, want: "low", wantWork: "low", newGoal: true},
		{name: "a wrap-up after a shell command runs alone", tier: "xhigh", mode: "ultracode", transcript: shell, prompt: "write the commit message",
			jev: fa{tier: "low", conf: 0.95, ultra: 0.9, rel: "wrap_up", relP: 0.9}, want: "low", wantWork: "xhigh", wantWorkMode: "ultracode"},
		{name: "mid-turn, above a lower work: not below the turn", tier: "xhigh", work: "medium", transcript: busy, prompt: "btw the staging DB is read-only",
			jev: fa{tier: "low", conf: 0.98, rel: "inform"}, want: "xhigh", wantWork: "xhigh"},
		{name: "a peer message never lowers", tier: "xhigh", prompt: `<cross-session-message from="docs">FYI the staging API moved to v2 [effort:low]</cross-session-message>`,
			jev: fa{tier: "low", conf: 0.95, rel: "new_task"}, want: "xhigh", wantWork: "xhigh"},
		{name: "a prompt quoting the peer phrase is the user's", tier: "xhigh", prompt: "now add an eval case whose task is 'Another Claude session sent a message: rebase'",
			jev: fa{tier: "low", conf: 0.95, rel: "new_task"}, want: "low", wantWork: "low", newGoal: true},
	} {
		t.Run(c.name, func(t *testing.T) {
			sid := fmt.Sprint("wip", i)
			workSession(t, env, sid, c.tier, c.mode, cmp.Or(c.work, c.tier))
			fj.answers = []fa{c.jev}
			n := fj.calls()
			in := map[string]any{"session_id": sid, "prompt": c.prompt, "cwd": t.TempDir()}
			if c.transcript != "" {
				in["transcript_path"] = c.transcript
			}
			run(t, env, "decide", in)
			if fj.calls() != n+1 {
				t.Fatalf("%d Jev calls", fj.calls()-n)
			}
			q := fj.last().Questions
			if q[jev.QRelation].Type != "choice" {
				t.Errorf("no relation question: %v", q)
			}
			if c.ask != "" && q[c.ask].Type != "noul" {
				t.Errorf("no %s question: %v", c.ask, q)
			}
			s, _ := env.State.Load(sid)
			if s.Main.Tier != c.want || s.Main.Mode != c.wantMode || s.Pin != "" {
				t.Errorf("decision %s +%q (pin %q), want %s +%q", s.Main.Tier, s.Main.Mode, s.Pin, c.want, c.wantMode)
			}
			if eff := env.Catalog.Tier(catalog.ScopeMain, s.Main.Tier).Effort; s.Main.Effort != eff {
				t.Errorf("tier %s stored with effort %s", s.Main.Tier, s.Main.Effort)
			}
			if w := s.Work; w == nil || w.Tier != c.wantWork || w.Mode != c.wantWorkMode || (w.Goal != workGoal) != c.newGoal {
				t.Errorf("work in progress %+v, want %s +%q (new goal %v)", w, c.wantWork, c.wantWorkMode, c.newGoal)
			}
		})
	}
}

// A go-ahead carries the work in progress on: after a side question
// lowered the tier, "vas-y" brings the work's tier and mode back without
// asking Jev; after a wrap-up it is routed (Jev's relation says whether it
// reopens the work); a go-ahead to a proposal is routed, not below the
// work.
func TestGoAheadRestoresWork(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	cwd := t.TempDir()
	decide := func(sid, p, tp string) {
		run(t, env, "decide", map[string]any{"session_id": sid, "prompt": p, "cwd": cwd, "transcript_path": tp})
	}
	// A side question answered at low (an older session, or one Jev read as
	// separate); the work in progress is still xhigh.
	workSession(t, env, "g1", "low", "", "xhigh")
	n := fj.calls()
	decide("g1", "Oui, vas-y !", "")
	s, _ := env.State.Load("g1")
	if fj.calls() != n || s.Main.Tier != "xhigh" || s.Main.Effort != "xhigh" || s.PendingEffort == nil || s.PendingEffort.Effort != "xhigh" {
		t.Fatalf("go-ahead after a side question: %d calls, %+v, pending %+v", fj.calls()-n, s.Main, s.PendingEffort)
	}
	all, _ := ledger.Decisions(env.Cfg.Ledger)
	if d := all[len(all)-1]; d.Hold != "go-ahead: back to the work in progress" || d.From != "low" || d.Chosen != "xhigh" || d.Kept {
		t.Errorf("ledger = %+v", d)
	}
	// The same flow, live: a side question in an ultracode session runs
	// without the mode, the go-ahead restores it.
	workSession(t, env, "g2", "xhigh", "ultracode", "xhigh")
	fj.answers = []fa{{tier: "low", conf: 0.95, ultra: 0.9, rel: "side_question"}}
	decide("g2", "how many handlers are left?", "")
	if s, _ = env.State.Load("g2"); s.Main.Tier != "xhigh" || s.Main.Mode != "" || s.UltracodeOn || s.Work.Mode != "ultracode" {
		t.Fatalf("side question: %+v, work %+v", s.Main, s.Work)
	}
	n = fj.calls()
	decide("g2", "ok, go", "")
	if s, _ = env.State.Load("g2"); fj.calls() != n || s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" || !s.UltracodeOn {
		t.Fatalf("go-ahead after a side question: %+v", s.Main)
	}
	// Unchanged: only logged as kept.
	decide("g2", "continue", "")
	if s, _ = env.State.Load("g2"); fj.calls() != n || s.Main.Tier != "xhigh" {
		t.Fatalf("plain go-ahead: %+v", s.Main)
	}
	// A side question answered above the work (ultrathink) raised that
	// answer only: the go-ahead goes back to the work's level.
	workSession(t, env, "g5", "low", "", "low")
	fj.answers = []fa{{tier: "low", conf: 0.9, rel: "side_question"}}
	decide("g5", "ultrathink: is the rename safe for the plugin API?", "")
	if s, _ = env.State.Load("g5"); s.Main.Tier != "xhigh" || s.Work.Tier != "low" {
		t.Fatalf("ultrathink side question: %+v, work %+v", s.Main, s.Work)
	}
	n = fj.calls()
	decide("g5", "ok, continue", "")
	if s, _ = env.State.Load("g5"); fj.calls() != n || s.Main.Tier != "low" {
		t.Errorf("go-ahead after an ultrathink side question: %+v", s.Main)
	}
	// After a wrap-up, a go-ahead or an acknowledgement is routed: "looks
	// good." on a done xhigh fix (held-out run 1 carried it at xhigh) gets
	// its own level; "vas-y" Jev reads as more work reopens it.
	warmSession(t, env, "g4", "xhigh", 300_000)
	fj.answers = []fa{{tier: "low", conf: 0.95, rel: "wrap_up"}}
	decide("g4", "résume ce que tu as fait", "")
	n = fj.calls()
	fj.answers = []fa{{tier: "low", conf: 0.95, rel: "aside", relP: 0.9}}
	decide("g4", "looks good.", "")
	if s, _ = env.State.Load("g4"); fj.calls() != n+1 || fj.last().Questions[jev.QRelation].Type != "choice" || s.Main.Tier != "low" || s.Work == nil || !s.Work.Done || s.Work.Tier != "xhigh" {
		t.Fatalf("acknowledgement of a done work (%d calls): %+v, work %+v", fj.calls()-n, s.Main, s.Work)
	}
	fj.answers = []fa{{tier: "low", conf: 0.95, rel: "continue"}}
	decide("g4", "vas-y", "")
	if s, _ = env.State.Load("g4"); s.Main.Tier != "xhigh" || s.Work.Done || s.Work.Tier != "xhigh" {
		t.Fatalf("go-ahead reopening a done work: %+v, work %+v", s.Main, s.Work)
	}
	n = fj.calls()
	// A go-ahead to a proposal is routed, without the relation question,
	// and not below the work in progress.
	tp := filepath.Join(cwd, "t.jsonl")
	os.WriteFile(tp, []byte(`{"type":"assistant","message":{"role":"assistant","stop_reason":"end_turn","content":[{"type":"text","text":"Both call sites read the lease without the lock. Want me to fix the second one too?"}]}}`+"\n"), 0o600)
	workSession(t, env, "g3", "xhigh", "", "xhigh")
	fj.answers = []fa{{tier: "low", conf: 0.9}}
	decide("g3", "yes", tp)
	if s, _ = env.State.Load("g3"); fj.calls() != n+1 || s.Main.Tier != "xhigh" || fj.last().Questions[jev.QRelation].Type != "" {
		t.Fatalf("go-ahead to a proposal: %+v, questions %v", s.Main, fj.last().Questions)
	}
	for _, p := range []string{"oui, vas-y", "ok, go", "yes, do it", "Parfait, fonce !", "let's go", "go for it", "ship it", "on y va", "c'est parti", "oui continue", "continue then"} {
		if !router.GoAhead(p) {
			t.Errorf("GoAhead(%q) = false", p)
		}
	}
	for _, p := range []string{"continue?", "go, and also add rate limiting", "oui mais garde l'ancienne API", "continue the refactor of the payment module"} {
		if router.GoAhead(p) {
			t.Errorf("GoAhead(%q) = true", p)
		}
	}
}

// A pin ([effort:x], /effort) keeps the ultracode mode unless its effort
// is below the mode's own, and never erases the work in progress.
func TestPinsKeepTheMode(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	decide := func(p string) *state.Session {
		run(t, env, "decide", map[string]any{"session_id": "p1", "prompt": p, "cwd": t.TempDir()})
		s, _ := env.State.Load("p1")
		return s
	}
	workSession(t, env, "p1", "xhigh", "ultracode", "xhigh")
	if s := decide("[effort:max] go, this one matters"); s.Main.Tier != "max" || s.Main.Mode != "ultracode" || !s.Main.Workflows || s.Pin != "max" {
		t.Fatalf("[effort:max] in an ultracode session: %+v", s.Main)
	}
	if s := decide("[effort:high] now the easy part"); s.Main.Tier != "high" || s.Main.Mode != "" || s.Work == nil || s.Work.Tier != "xhigh" || s.Work.Mode != "ultracode" {
		t.Fatalf("[effort:high]: %+v, work %+v", s.Main, s.Work)
	}
}

// A model asked for in words runs the work in progress, not the session:
// follow-ups (and wrap-ups) stay on it at the effort routing picks, a
// separate new task goes back to the tiers, and only the [model:x] tag
// pins. Mentions, and requests Jev is not sure enough of (below
// meta.explicit_model_threshold), change nothing.
func TestWorkModel(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	const sonnet = "claude-sonnet-5-5"
	cwd := t.TempDir()
	decide := func(sid, p string, a fa) *state.Session {
		t.Helper()
		fj.answers = []fa{a}
		run(t, env, "decide", map[string]any{"session_id": sid, "prompt": p, "cwd": cwd})
		s, _ := env.State.Load(sid)
		return s
	}
	model := func(p float64) map[string]float64 { return map[string]float64{"model_" + sonnet: p} }
	workSession(t, env, "m1", "high", "", "high")
	s := decide("m1", "passe sur sonnet pour la suite des exports", fa{tier: "medium", conf: 0.9, rel: "extend", x: model(0.95)})
	if s.Pin != "" || s.PinModel != "" || s.Main.Model != sonnet || s.Main.Tier != state.PinnedTier || s.Main.Effort != "high" || s.Work.Model != sonnet || s.Work.Tier != "high" || s.Work.Goal != workGoal {
		t.Fatalf("model asked in words: pin %q/%q, main %+v, work %+v", s.Pin, s.PinModel, s.Main, s.Work)
	}
	if st := fj.last().State.(map[string]any); st["current"].(map[string]any)["tier"] != "high" {
		t.Errorf("state before the switch = %v", st["current"])
	}
	// A follow-up stays on it, at the level routing picks (never below the
	// work's): Jev is still asked, and sees the model in force.
	s = decide("m1", "and handle the retry storm when the pool is exhausted too", fa{tier: "xhigh", conf: 0.9, rel: "extend"})
	if s.Main.Model != sonnet || s.Main.Effort != "xhigh" || s.Work.Tier != "xhigh" || s.Work.Model != sonnet {
		t.Fatalf("follow-up on the work's model: %+v, work %+v", s.Main, s.Work)
	}
	if cur := fj.last().State.(map[string]any)["current"].(map[string]any); cur["model"] != "Sonnet 5.5" || cur["tier"] != nil {
		t.Errorf("current = %v", cur)
	}
	s = decide("m1", "is CI green yet?", fa{tier: "low", conf: 0.9, rel: "side_question"})
	if s.Main.Model != sonnet || s.Main.Effort != "xhigh" {
		t.Fatalf("side question: %+v", s.Main)
	}
	all, _ := ledger.Decisions(env.Cfg.Ledger)
	if d := all[len(all)-1]; !d.Kept || d.KeepReason != "same model and effort" {
		t.Errorf("unchanged decision on the work's model: %+v", d)
	}
	// A wrap-up gets its own level, still on the work's model.
	s = decide("m1", "write the commit message", fa{tier: "low", conf: 0.95, rel: "wrap_up"})
	if s.Main.Model != sonnet || s.Main.Effort != "low" || s.Work.Model != sonnet || s.Work.Tier != "xhigh" {
		t.Fatalf("wrap-up: %+v, work %+v", s.Main, s.Work)
	}
	// [effort:x] on it pins that model at that effort.
	s = decide("m1", "[effort:high] now the easy part", fa{tier: "low", conf: 0.9, rel: "extend"})
	if s.PinModel != sonnet || s.Pin != "high" || s.Main.Model != sonnet || s.Main.Effort != "high" {
		t.Fatalf("[effort:high] on the work's model: pin %q/%q, %+v", s.Pin, s.PinModel, s.Main)
	}
	decide("m1", "[effort:auto] ok", fa{tier: "high", conf: 0.9, rel: "extend"})
	// A separate new task goes back to the tiers.
	s = decide("m1", "now rename the config loader to settings", fa{tier: "medium", conf: 0.9, rel: "new_task"})
	if s.Main.Model != "claude-opus-5-5" || s.Main.Tier != "medium" || s.Work.Model != "" || s.Work.Tier != "medium" {
		t.Fatalf("new task: %+v, work %+v", s.Main, s.Work)
	}

	// Asked for a wrap-up, a side question or an aside, a model runs that
	// answer only: the work stays on its own.
	for i, c := range []struct{ prompt, rel string }{
		{"write the commit message with Sonnet", "wrap_up"},
		{"is CI green yet? Sonnet can answer that one", "side_question"},
		{"quick unrelated one for Sonnet: what does HTTP 409 mean?", "aside"},
	} {
		sid := fmt.Sprint("mt", i)
		workSession(t, env, sid, "xhigh", "", "xhigh")
		s = decide(sid, c.prompt, fa{tier: "low", conf: 0.9, rel: c.rel, x: model(0.95)})
		if s.Main.Model != sonnet || s.Work.Model != "" || s.Work.Tier != "xhigh" || s.Work.Done != (c.rel == "wrap_up") {
			t.Errorf("%s asking for Sonnet: %+v, work %+v", c.rel, s.Main, s.Work)
		}
	}

	// Asked for the rest of the work as it stands, the model keeps the
	// work's level (held-out run 1: "fais le reste avec Sonnet, pas besoin
	// d'Opus pour du CSS" on medium work went to high); with more work to
	// it (extend), routing may raise it.
	workSession(t, env, "m5", "medium", "", "medium")
	s = decide("m5", "fais le reste avec Sonnet, pas besoin d'Opus pour du CSS", fa{tier: "high", conf: 0.3, rel: "continue", x: model(0.88)})
	if s.Main.Model != sonnet || s.Main.Effort != "medium" || s.Work.Model != sonnet || s.Work.Tier != "medium" {
		t.Errorf("model for the rest: %+v, work %+v", s.Main, s.Work)
	}
	workSession(t, env, "m6", "medium", "", "medium")
	s = decide("m6", "switch to Sonnet and also backfill the old rows, that's the part that can corrupt data", fa{tier: "xhigh", conf: 0.9, rel: "extend", x: model(0.9)})
	if s.Main.Model != sonnet || s.Main.Effort != "xhigh" || s.Work.Tier != "xhigh" {
		t.Errorf("model with more work: %+v, work %+v", s.Main, s.Work)
	}

	// Asking for the tiers' model goes back to routing on the tiers.
	workSession(t, env, "m2", "high", "", "high")
	decide("m2", "use sonnet for this part", fa{tier: "high", conf: 0.9, rel: "extend", x: model(0.95)})
	s = decide("m2", "ok switch back to opus for the rest", fa{tier: "high", conf: 0.9, rel: "extend", x: map[string]float64{"model_claude-opus-5-5": 0.96}})
	if s.Main.Model != "claude-opus-5-5" || s.Main.Tier != "high" || s.Work.Model != "" {
		t.Fatalf("back to opus: %+v, work %+v", s.Main, s.Work)
	}
	// Only mentioned, or not sure enough: routing goes on as before.
	for i, c := range []struct {
		prompt string
		p      float64
	}{{"is sonnet cheaper than opus for this?", 0.05}, {"sonnet 5.5 est sorti, tu en penses quoi ?", 0.7}} {
		sid := fmt.Sprint("m3", i)
		workSession(t, env, sid, "high", "", "high")
		s = decide(sid, c.prompt, fa{tier: "high", conf: 0.9, rel: "side_question", x: model(c.p)})
		if q := fj.last().Questions["explicit_model_"+sonnet]; q.Type != "noul" || !strings.Contains(q.Instructions, "run on the Sonnet 5.5 model itself") {
			t.Errorf("model question = %+v", q)
		}
		if s.PinModel != "" || s.Main.Model != "claude-opus-5-5" || s.Work.Model != "" {
			t.Errorf("%q moved the work to %s: %+v", c.prompt, s.Main.Model, s.Work)
		}
	}
	// The [model:x] tag is still a lasting pin.
	workSession(t, env, "m4", "high", "", "high")
	s = decide("m4", "[model:sonnet] summarize yesterday's logs", fa{tier: "low", conf: 0.9, rel: "new_task"})
	if s.PinModel != sonnet || s.Main.Model != sonnet {
		t.Fatalf("[model:sonnet]: pin %q, %+v", s.PinModel, s.Main)
	}
}

// A new task below the work in progress pauses it (a detour); a prompt
// that goes back to it restores its tier, mode, model and goal. Another
// new task, or two hours, drop it.
func TestPausedWork(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	cwd := t.TempDir()
	decide := func(sid, p string, a fa) *state.Session {
		t.Helper()
		fj.answers = []fa{a}
		run(t, env, "decide", map[string]any{"session_id": sid, "prompt": p, "cwd": cwd})
		s, _ := env.State.Load(sid)
		return s
	}
	offered := func() bool {
		opts, _ := fj.last().Questions[jev.QRelation].Criteria.(map[string]any)
		_, ok := opts[catalog.RelationResume]
		return ok
	}
	workSession(t, env, "d1", "xhigh", "ultracode", "xhigh")
	env.State.Update("d1", func(s *state.Session) bool { s.Work.Model = "claude-sonnet-5-5"; return true })
	s := decide("d1", "quick one: fix the typo in the README title", fa{tier: "low", conf: 0.95, rel: "new_task"})
	if offered() {
		t.Error("resume offered without paused work")
	}
	if p := s.Paused; s.Main.Tier != "low" || s.Main.Mode != "" || s.Work.Tier != "low" || p == nil || p.Tier != "xhigh" || p.Mode != "ultracode" || p.Model != "claude-sonnet-5-5" || p.Goal != workGoal {
		t.Fatalf("detour: %+v, work %+v, paused %+v", s.Main, s.Work, s.Paused)
	}
	// A follow-up of the detour keeps it; the paused work waits, and Jev
	// may relate the prompt to it.
	s = decide("d1", "and the one in CONTRIBUTING too", fa{tier: "low", conf: 0.95, rel: "extend"})
	st := fj.last().State.(map[string]any)
	if pw, _ := st["paused_work"].(map[string]any); !offered() || pw["goal"] != workGoal || pw["level"] != "xhigh" || s.Paused == nil {
		t.Fatalf("paused work in the state: %v (resume offered %v)", st["paused_work"], offered())
	}
	s = decide("d1", "ok, back to the pool race", fa{tier: "low", conf: 0.9, rel: "resume", relP: 0.9})
	if s.Main.Tier != state.PinnedTier || s.Main.Model != "claude-sonnet-5-5" || s.Main.Effort != "xhigh" || s.Main.Mode != "ultracode" || s.Paused != nil ||
		s.Work.Tier != "xhigh" || s.Work.Mode != "ultracode" || s.Work.Model != "claude-sonnet-5-5" || s.Work.Goal != workGoal {
		t.Fatalf("resume: %+v, work %+v, paused %+v", s.Main, s.Work, s.Paused)
	}
	all, _ := ledger.Decisions(env.Cfg.Ledger)
	if d := all[len(all)-1]; d.Work != "resumed" || d.PausedTier != "xhigh" || !strings.HasPrefix(d.Hold, "back to the paused work (resume 0.90)") {
		t.Errorf("ledger = %+v", d)
	}

	// Another new task drops the paused work, unless it is below it too
	// (the detour goes on); and so does time.
	workSession(t, env, "d2", "xhigh", "", "xhigh")
	decide("d2", "quick one: fix the typo in the README title", fa{tier: "low", conf: 0.95, rel: "new_task"})
	if s = decide("d2", "and the broken link in the install section too", fa{tier: "low", conf: 0.95, rel: "new_task"}); s.Paused == nil || s.Paused.Goal != workGoal || s.Work.Tier != "low" {
		t.Fatalf("a detour of the detour: work %+v, paused %+v", s.Work, s.Paused)
	}
	if s = decide("d2", "now design how to shard the job queue", fa{tier: "xhigh", conf: 0.9, rel: "new_task"}); s.Paused != nil || s.Work.Tier != "xhigh" {
		t.Fatalf("second new task: work %+v, paused %+v", s.Work, s.Paused)
	}
	workSession(t, env, "d3", "xhigh", "", "xhigh")
	decide("d3", "quick one: fix the typo in the README title", fa{tier: "low", conf: 0.95, rel: "new_task"})
	env.State.Update("d3", func(s *state.Session) bool { s.Paused.Since = time.Now().Add(-3 * time.Hour); return true })
	s = decide("d3", "back to the pool race", fa{tier: "low", conf: 0.9, rel: "continue"})
	if st := fj.last().State.(map[string]any); st["paused_work"] != nil || offered() || s.Paused != nil || s.Main.Tier != "low" {
		t.Fatalf("expired paused work: %v, %+v, paused %+v", st["paused_work"], s.Main, s.Paused)
	}
	// A new task that doesn't go below the work pauses nothing.
	workSession(t, env, "d4", "medium", "", "medium")
	if s = decide("d4", "next: find why refunds are counted twice under load", fa{tier: "xhigh", conf: 0.9, rel: "new_task"}); s.Paused != nil {
		t.Fatalf("harder new task paused %+v", s.Paused)
	}
}

// The work in progress survives a compaction, and the decision on the
// summary can't go below it.
func TestCompactionKeepsWork(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	workSession(t, env, "c2", "xhigh", "ultracode", "xhigh")
	tp := filepath.Join(t.TempDir(), "t.jsonl")
	os.WriteFile(tp, []byte(`{"type":"system","subtype":"compact_boundary"}`+"\n"+
		`{"type":"user","isCompactSummary":true,"message":{"role":"user","content":"We were auditing every handler for injection; next: the admin routes."}}`+"\n"), 0o600)
	fj.answers = []fa{{tier: "low", conf: 0.9, ultra: 0.1}}
	t.Setenv(CompactEnv, fmt.Sprint(time.Now().UnixNano()))
	run(t, env, "session-start", map[string]any{"session_id": "c2", "source": "compact", "transcript_path": tp})
	s, _ := env.State.Load("c2")
	if s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" || s.Work == nil || s.Work.Goal != workGoal {
		t.Fatalf("after compaction: %+v, work %+v", s.Main, s.Work)
	}
	if q := fj.last().Questions; q[jev.QRelation].Type != "" {
		t.Errorf("relation asked without a prompt: %v", q)
	}
	// The next prompt sees the work in progress (recent prompts are gone).
	t.Setenv(CompactEnv, "")
	fj.answers = []fa{{tier: "medium", conf: 0.9, ultra: 0.1, rel: "continue"}}
	run(t, env, "decide", map[string]any{"session_id": "c2", "prompt": "on reprend", "cwd": t.TempDir(), "transcript_path": tp})
	st := fj.last().State.(map[string]any)
	if wip, _ := st["work_in_progress"].(map[string]any); st["phase"] != "post_compact" || wip["goal"] != workGoal || wip["level"] != "xhigh" {
		t.Errorf("state = %v", st)
	}
	if s, _ = env.State.Load("c2"); s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" {
		t.Errorf("after the first prompt: %+v", s.Main)
	}

	// A work a wrap-up closed holds nothing after a compaction: the
	// summary gets its own level, without the work's mode.
	workSession(t, env, "c3", "low", "", "xhigh")
	env.State.Update("c3", func(s *state.Session) bool { s.Work.Mode, s.Work.Done = "ultracode", true; return true })
	fj.answers = []fa{{tier: "low", conf: 0.9, ultra: 0.9}}
	t.Setenv(CompactEnv, fmt.Sprint(time.Now().UnixNano()))
	run(t, env, "session-start", map[string]any{"session_id": "c3", "source": "compact", "transcript_path": tp})
	if s, _ = env.State.Load("c3"); s.Main.Tier != "low" || s.Main.Mode != "" || !s.Work.Done || s.Work.Mode != "ultracode" {
		t.Errorf("compaction after a wrap-up: %+v, work %+v", s.Main, s.Work)
	}
}

// Requests in words: an effort talked about for something else (a
// subagent, a tuning file, a quoted prompt) must not lower the work; an
// effort below the work needs a surer yes (router.LowerEffortP); an effort
// asked for a wrap-up or a side question is for that answer only; an
// effort asked in words keeps the work's mode and lets Jev turn one on.
func TestRequestsInWords(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	cwd := t.TempDir()
	decide := func(sid, p string, a fa) *state.Session {
		t.Helper()
		fj.answers = []fa{a}
		run(t, env, "decide", map[string]any{"session_id": sid, "prompt": p, "cwd": cwd})
		s, _ := env.State.Load(sid)
		return s
	}
	low := func(p float64) map[string]float64 { return map[string]float64{"effort_low": p} }

	// A mention Jev half-reads as a request (0.88, as live for these
	// prompts) doesn't lower xhigh work; a real one (0.95) does.
	for i, c := range []struct {
		prompt string
		p      float64
		want   string
	}{
		{"set it to low in the tuning file for the subagents, then keep going on the deadlock", 0.88, "xhigh"},
		{"use low for the explore agents in the workflow, and keep going on the race", 0.89, "xhigh"},
		{"passe en low pour la suite, c'est mécanique", 0.95, "low"},
	} {
		sid := fmt.Sprint("lo", i)
		workSession(t, env, sid, "xhigh", "", "xhigh")
		s := decide(sid, c.prompt, fa{tier: "high", conf: 0.9, rel: "extend", x: low(c.p)})
		if s.Main.Tier != c.want || s.Work.Tier != c.want {
			t.Errorf("%q (effort_low %.2f): decision %s, work %s, want %s", c.prompt, c.p, s.Main.Tier, s.Work.Tier, c.want)
		}
		if q := fj.last().Questions["explicit_effort_low"]; !strings.Contains(q.Instructions, "itself") || !strings.Contains(q.Instructions, "its own work") {
			t.Errorf("effort question = %q", q.Instructions)
		}
	}
	// An effort above the work needs only meta.explicit_threshold.
	workSession(t, env, "up", "medium", "", "medium")
	if s := decide("up", "fais la suite en xhigh", fa{tier: "medium", conf: 0.9, rel: "extend", x: map[string]float64{"effort_xhigh": 0.85}}); s.Main.Tier != "xhigh" || s.Work.Tier != "xhigh" {
		t.Errorf("raise at 0.85: %s, work %s", s.Main.Tier, s.Work.Tier)
	}

	// Asked for a wrap-up or a side question: that answer only.
	workSession(t, env, "wu", "xhigh", "", "xhigh")
	if s := decide("wu", "write the commit message, in low effort", fa{tier: "low", conf: 0.95, rel: "wrap_up", x: low(0.95)}); s.Main.Tier != "low" || s.Work.Tier != "xhigh" {
		t.Fatalf("effort for a wrap-up: %s, work %s", s.Main.Tier, s.Work.Tier)
	}
	if s := decide("wu", "ok, continue", fa{tier: "low", conf: 0.95, rel: "continue"}); s.Main.Tier != "xhigh" || s.Work.Done {
		t.Errorf("go-ahead after the wrap-up: %s, work %+v", s.Main.Tier, s.Work)
	}
	workSession(t, env, "sq", "xhigh", "ultracode", "xhigh")
	s := decide("sq", "why did the retry fail there? answer at low effort", fa{tier: "low", conf: 0.95, ultra: 0.1, rel: "side_question", x: low(0.95)})
	if s.Main.Tier != "low" || s.Main.Mode != "" || s.Work.Tier != "xhigh" || s.Work.Mode != "ultracode" {
		t.Errorf("effort for a side question: %+v, work %+v", s.Main, s.Work)
	}

	// The mode: an effort asked in words doesn't turn it off, nor stop
	// Jev turning it on, unless the mode would raise that effort.
	markJev(t, env, "m1")
	if s = decide("m1", "Audite tout le repo en xhigh pour les injections SQL, module par module", fa{tier: "xhigh", conf: 0.9, ultra: 0.95, x: map[string]float64{"effort_xhigh": 0.95}}); s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" {
		t.Errorf("first prompt with an effort: %+v", s.Main)
	}
	markJev(t, env, "m2")
	if s = decide("m2", "Audit the whole repo for SQL injections at high effort", fa{tier: "xhigh", conf: 0.9, ultra: 0.95, x: map[string]float64{"effort_high": 0.95}}); s.Main.Tier != "high" || s.Main.Mode != "" {
		t.Errorf("a mode that would raise the asked effort: %+v", s.Main)
	}
	workSession(t, env, "m3", "xhigh", "ultracode", "xhigh")
	decide("m3", "write the commit message", fa{tier: "low", conf: 0.95, ultra: 0.1, rel: "wrap_up"})
	s = decide("m3", "ok, maintenant continue en xhigh", fa{tier: "high", conf: 0.9, ultra: 0.1, rel: "continue", x: map[string]float64{"effort_xhigh": 0.95}})
	if s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" || s.Work.Mode != "ultracode" {
		t.Errorf("continue en xhigh after a wrap-up: %+v, work %+v", s.Main, s.Work)
	}

	// Refusing the mode, in the words people use.
	for i, p := range []string{"no need for ultracode here, just fix the error message", "n'utilise pas ultracode pour ça, corrige juste le message",
		"skip ultracode for this one, just fix the message", "ultracode isn't needed, just fix the message"} {
		sid := fmt.Sprint("off", i)
		workSession(t, env, sid, "xhigh", "ultracode", "xhigh")
		s = decide(sid, p, fa{tier: "low", conf: 0.9, ultra: 0.1, rel: "extend", x: map[string]float64{"mode_off": 0.95}})
		if s.Main.Mode != "" || s.Main.Tier != "xhigh" {
			t.Errorf("%q: %+v", p, s.Main)
		}
	}
	// Efforts asked in words the old regex missed.
	for i, p := range []string{"set the effort to medium for the rest, it's mechanical", "mets l'effort à medium pour la suite", "effort moyen pour la suite"} {
		sid := fmt.Sprint("mid", i)
		workSession(t, env, sid, "xhigh", "", "xhigh")
		if s = decide(sid, p, fa{tier: "high", conf: 0.9, rel: "extend", x: map[string]float64{"effort_medium": 0.95}}); s.Main.Tier != "medium" {
			t.Errorf("%q: %s", p, s.Main.Tier)
		}
	}
}

// In metadata privacy Jev never sees the words: only the forms that ask
// for more thinking whatever the context count, and they raise the turn,
// never the work in progress.
func TestMoreThinkingInMetadataMode(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	env.Cfg.Privacy = "metadata"
	cwd := t.TempDir()
	decide := func(p string, a fa) *state.Session {
		t.Helper()
		fj.answers = []fa{a}
		run(t, env, "decide", map[string]any{"session_id": "md", "prompt": p, "cwd": cwd})
		s, _ := env.State.Load("md")
		return s
	}
	workSession(t, env, "md", "high", "", "high")
	if s := decide("lis le fichier de config en profondeur et dis-moi ce qui cloche", fa{tier: "medium", conf: 0.9, rel: "side_question"}); s.Main.Tier != "high" || s.Work.Tier != "high" {
		t.Errorf("en profondeur: %s, work %s", s.Main.Tier, s.Work.Tier)
	}
	if s := decide("le CPU tourne à fond depuis ce matin, pour info", fa{tier: "low", conf: 0.9, rel: "inform"}); s.Main.Tier != "high" || s.Work.Tier != "high" {
		t.Errorf("à fond: %s, work %s", s.Main.Tier, s.Work.Tier)
	}
	if s := decide("réfléchis bien avant de toucher au verrou", fa{tier: "medium", conf: 0.9, rel: "extend"}); s.Main.Tier != "xhigh" || s.Work.Tier != "high" {
		t.Errorf("réfléchis bien: %s, work %s", s.Main.Tier, s.Work.Tier)
	}
	if q := fj.last().Questions; len(q) == 0 || q["explicit_effort_more"].Type != "" {
		t.Errorf("questions in metadata mode: %v", q)
	}
}

// After a detour, a bare go-ahead goes back to the paused work when it
// needs more: its tier, mode, model and goal come back, without asking
// Jev; a go-ahead to a proposal is routed, not below it. Jev's resume
// needs relation_separate_threshold.
func TestDetourThenGoAhead(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	cwd := t.TempDir()
	decide := func(sid, p, tp string, a fa) *state.Session {
		t.Helper()
		fj.answers = []fa{a}
		run(t, env, "decide", map[string]any{"session_id": sid, "prompt": p, "cwd": cwd, "transcript_path": tp})
		s, _ := env.State.Load(sid)
		return s
	}
	detour := func(sid string) {
		t.Helper()
		workSession(t, env, sid, "xhigh", "ultracode", "xhigh")
		if s := decide(sid, "quick one: fix the typo in the README title", "", fa{tier: "low", conf: 0.95, ultra: 0.05, rel: "new_task"}); s.Paused == nil || s.Main.Tier != "low" {
			t.Fatalf("detour: %+v, paused %+v", s.Main, s.Paused)
		}
	}
	for i, p := range []string{"ok, continue", "vas-y", "go"} {
		sid := fmt.Sprint("dg", i)
		detour(sid)
		n := fj.calls()
		s := decide(sid, p, "", fa{tier: "low", conf: 0.95, rel: "continue"})
		if fj.calls() != n || s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" || s.Paused != nil || s.Work.Goal != workGoal || s.Work.Mode != "ultracode" {
			t.Fatalf("%q after a detour (%d calls): %+v, work %+v, paused %+v", p, fj.calls()-n, s.Main, s.Work, s.Paused)
		}
		// The next follow-up holds the resumed work.
		if s = decide(sid, "and handle the case where the pool is empty", "", fa{tier: "medium", conf: 0.9, ultra: 0.05, rel: "extend"}); s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" {
			t.Errorf("extension after the go-ahead: %+v", s.Main)
		}
	}
	all, _ := ledger.Decisions(env.Cfg.Ledger)
	if d := all[len(all)-2]; d.Work != router.WorkResumed || d.Chosen != "xhigh" || d.Mode != "ultracode" {
		t.Errorf("ledger of the go-ahead = %+v", d)
	}

	// A go-ahead to a proposal after a detour: routed, floored at the
	// paused work, which it resumes.
	tp := filepath.Join(cwd, "t.jsonl")
	os.WriteFile(tp, []byte(`{"type":"assistant","message":{"role":"assistant","stop_reason":"end_turn","content":[{"type":"text","text":"Typo fixed. Want me to get back to the pool race?"}]}}`+"\n"), 0o600)
	detour("dp")
	n := fj.calls()
	s := decide("dp", "yes", tp, fa{tier: "low", conf: 0.9, ultra: 0.05})
	if fj.calls() != n+1 || fj.last().Questions[jev.QRelation].Type != "" || s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" || s.Paused != nil || s.Work.Goal != workGoal {
		t.Fatalf("go-ahead to a proposal after a detour: %+v, work %+v, paused %+v", s.Main, s.Work, s.Paused)
	}

	// Once the detour was wrapped up ("commit that"), a go-ahead still goes
	// back to the paused work without asking Jev (live, Jev read "vas-y" as
	// continue and reopened the committed typo fix), and so does a go-ahead
	// to a proposal to go back to it. A done work alone is routed
	// (TestGoAheadRestoresWork).
	wrapped := func(sid string) {
		t.Helper()
		detour(sid)
		if s := decide(sid, "commit that", "", fa{tier: "low", conf: 0.95, rel: "wrap_up"}); !s.Work.Done || s.Paused == nil || s.Main.Tier != "low" {
			t.Fatalf("detour wrapped up: %+v, work %+v, paused %+v", s.Main, s.Work, s.Paused)
		}
	}
	for i, p := range []string{"vas-y", "oui, continue", "go", "ok, go on"} {
		sid := fmt.Sprint("wd", i)
		wrapped(sid)
		n := fj.calls()
		s := decide(sid, p, "", fa{tier: "low", conf: 0.9, ultra: 0.6, rel: "continue", relP: 0.75})
		if fj.calls() != n || s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" || s.Paused != nil || s.Work.Goal != workGoal || s.Work.Done || s.Work.Mode != "ultracode" {
			t.Errorf("%q after a wrapped-up detour (%d calls): %+v, work %+v, paused %+v", p, fj.calls()-n, s.Main, s.Work, s.Paused)
		}
	}
	os.WriteFile(tp, []byte(`{"type":"assistant","message":{"role":"assistant","stop_reason":"end_turn","content":[{"type":"text","text":"Committed as docs: fix the README title typo. Shall I get back to the pool race?"}]}}`+"\n"), 0o600)
	for i, p := range []string{"yes", "oui"} {
		sid := fmt.Sprint("wp", i)
		wrapped(sid)
		n := fj.calls()
		s := decide(sid, p, tp, fa{tier: "low", conf: 0.9, ultra: 0.05})
		if fj.calls() != n+1 || fj.last().Questions[jev.QRelation].Type != "" || s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" || s.Paused != nil || s.Work.Goal != workGoal || s.Work.Done {
			t.Errorf("%q to going back after a wrapped-up detour: %+v, work %+v, paused %+v", p, s.Main, s.Work, s.Paused)
		}
	}

	// Typed while the detour still runs, a go-ahead goes on with the turn:
	// the paused work waits (the next "commit it" would otherwise close the
	// migration).
	detour("dm")
	n = fj.calls()
	if s = decide("dm", "go on", busyTranscript(t), fa{tier: "low", conf: 0.9}); fj.calls() != n || s.Main.Tier != "low" || s.Main.Mode != "" || s.Paused == nil || s.Paused.Goal != workGoal || s.Work.Goal == workGoal {
		t.Errorf("go-ahead typed mid-turn during a detour: %+v, work %+v, paused %+v", s.Main, s.Work, s.Paused)
	}

	// A resume Jev is unsure of (0.30, the other options at 0.10) is a
	// follow-up of the detour; a sure one goes back.
	detour("dw")
	if s = decide("dw", "and the one in CONTRIBUTING.md too", "", fa{tier: "low", conf: 0.9, ultra: 0.05, rel: "resume", relP: 0.3}); s.Main.Tier != "low" || s.Paused == nil || s.Work.Goal == workGoal {
		t.Errorf("weak resume: %+v, work %+v, paused %+v", s.Main, s.Work, s.Paused)
	}
	if s = decide("dw", "ok, back to the pool race", "", fa{tier: "low", conf: 0.9, ultra: 0.05, rel: "resume", relP: 0.6}); s.Main.Tier != "xhigh" || s.Paused != nil || s.Work.Goal != workGoal {
		t.Errorf("resume at 0.60: %+v, work %+v, paused %+v", s.Main, s.Work, s.Paused)
	}
}

// An aside (a question unrelated to the work) gets its own level for that
// turn and changes nothing; a wrap-up marks the work done, after which a
// question gets its own level too, and more work on it reopens it.
func TestAsideAndDoneWork(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	cwd := t.TempDir()
	decide := func(sid, p string, a fa) *state.Session {
		t.Helper()
		fj.answers = []fa{a}
		run(t, env, "decide", map[string]any{"session_id": sid, "prompt": p, "cwd": cwd})
		s, _ := env.State.Load(sid)
		return s
	}
	workSession(t, env, "a1", "xhigh", "ultracode", "xhigh")
	s := decide("a1", "autre chose : que veut dire le code HTTP 409 ?", fa{tier: "low", conf: 0.95, ultra: 0.02, rel: "aside"})
	if opts, _ := fj.last().Questions[jev.QRelation].Criteria.(map[string]any); opts[catalog.RelationAside] == nil {
		t.Errorf("aside not offered: %v", opts)
	}
	if s.Main.Tier != "low" || s.Main.Mode != "" || s.Work.Tier != "xhigh" || s.Work.Mode != "ultracode" || s.Work.Goal != workGoal || s.Work.Done || s.Paused != nil {
		t.Fatalf("aside: %+v, work %+v, paused %+v", s.Main, s.Work, s.Paused)
	}
	all, _ := ledger.Decisions(env.Cfg.Ledger)
	if d := all[len(all)-1]; d.Work != "" || d.Hold != "" || d.WorkTier != "xhigh" {
		t.Errorf("ledger of an aside = %+v", d)
	}
	if s = decide("a1", "ok, go", fa{}); s.Main.Tier != "xhigh" || s.Main.Mode != "ultracode" {
		t.Errorf("go-ahead after an aside: %+v", s.Main)
	}

	workSession(t, env, "w1", "xhigh", "", "xhigh")
	if s = decide("w1", "write the commit message", fa{tier: "low", conf: 0.95, rel: "wrap_up"}); s.Main.Tier != "low" || !s.Work.Done || s.Work.Tier != "xhigh" || s.Work.Goal != workGoal {
		t.Fatalf("wrap-up: %+v, work %+v", s.Main, s.Work)
	}
	if s = decide("w1", "is CI green on main now?", fa{tier: "low", conf: 0.95, rel: "side_question"}); s.Main.Tier != "low" || !s.Work.Done {
		t.Errorf("question after a wrap-up: %+v, work %+v", s.Main, s.Work)
	}
	if wip, _ := fj.last().State.(map[string]any)["work_in_progress"].(map[string]any); wip["done"] != true || wip["level"] != "xhigh" {
		t.Errorf("work_in_progress sent = %v", wip)
	}
	if s = decide("w1", "FYI the release is tomorrow", fa{tier: "low", conf: 0.95, rel: "inform"}); s.Main.Tier != "low" || !s.Work.Done {
		t.Errorf("fact after a wrap-up: %+v, work %+v", s.Main, s.Work)
	}
	// A remark typed while Claude commits a done ultracode work: held at
	// the turn's level, without bringing the work's mode back.
	workSession(t, env, "w3", "xhigh", "ultracode", "xhigh")
	decide("w3", "write the commit message", fa{tier: "low", conf: 0.95, ultra: 0.1, rel: "wrap_up"})
	fj.answers = []fa{{tier: "low", conf: 0.95, ultra: 0.1, rel: "extend"}}
	run(t, env, "decide", map[string]any{"session_id": "w3", "prompt": "oh and mention the ticket number", "cwd": cwd, "transcript_path": busyTranscript(t)})
	if s, _ = env.State.Load("w3"); s.Main.Tier != "low" || s.Main.Mode != "" || !s.Work.Done {
		t.Errorf("mid-turn remark on a done work: %+v, work %+v", s.Main, s.Work)
	}
	// On a cold turn a done ultracode work holds nothing: a fact or an
	// aside gets its own level, and the mode the work ran with is not in
	// force (Jev's yes turns it on only for work it can run).
	workSession(t, env, "w4", "xhigh", "ultracode", "xhigh")
	decide("w4", "write the commit message", fa{tier: "low", conf: 0.95, ultra: 0.1, rel: "wrap_up"})
	for _, c := range []struct{ prompt, rel string }{{"FYI the release is tomorrow", "inform"}, {"au fait, c'est quoi la différence entre rebase et merge ?", "aside"}} {
		env.State.Update("w4", func(s *state.Session) bool { s.ColdHint = true; return true })
		if s = decide("w4", c.prompt, fa{tier: "low", conf: 0.9, ultra: 0.9, rel: c.rel}); s.Main.Tier != "low" || s.Main.Mode != "" || !s.Work.Done || s.Work.Mode != "ultracode" {
			t.Errorf("%s on a done ultracode work, cold: %+v, work %+v", c.rel, s.Main, s.Work)
		}
	}
	// A new task below a done work pauses nothing.
	workSession(t, env, "w2", "xhigh", "", "xhigh")
	decide("w2", "write the commit message", fa{tier: "low", conf: 0.95, rel: "wrap_up"})
	if s = decide("w2", "now fix the typo in the README title", fa{tier: "low", conf: 0.95, rel: "new_task"}); s.Paused != nil || s.Work.Done || s.Work.Tier != "low" {
		t.Errorf("new task after a wrap-up: work %+v, paused %+v", s.Work, s.Paused)
	}
	// More work on it reopens it, at its level.
	if s = decide("w1", "also add a test for the empty pool", fa{tier: "medium", conf: 0.9, rel: "extend"}); s.Main.Tier != "xhigh" || s.Work.Done {
		t.Errorf("extension after a wrap-up: %+v, work %+v", s.Main, s.Work)
	}
	all, _ = ledger.Decisions(env.Cfg.Ledger)
	if d := all[len(all)-1]; d.Work != router.WorkReopened {
		t.Errorf("ledger of a reopening = %+v", d)
	}
	decide("w1", "write the commit message", fa{tier: "low", conf: 0.95, rel: "wrap_up"})
	if s = decide("w1", "ok, go", fa{tier: "low", conf: 0.95, rel: "continue"}); s.Main.Tier != "xhigh" || s.Work.Done {
		t.Errorf("go-ahead after a wrap-up: %+v, work %+v", s.Main, s.Work)
	}
	all, _ = ledger.Decisions(env.Cfg.Ledger)
	if d := all[len(all)-1]; d.Work != router.WorkReopened || d.Skipped {
		t.Errorf("ledger of a go-ahead reopening a done work = %+v", d)
	}
	// An acknowledgement is not more work: its own level, the work done.
	decide("w1", "write the commit message", fa{tier: "low", conf: 0.95, rel: "wrap_up"})
	if s = decide("w1", "ok", fa{tier: "low", conf: 0.95, rel: "aside"}); s.Main.Tier != "low" || !s.Work.Done {
		t.Errorf("ok after a wrap-up: %+v, work %+v", s.Main, s.Work)
	}
}

// A session that started pinned ([effort:max]) has no work in progress
// taken from that pin: once released, the prompt gets its own level.
func TestPinnedStartIsNoWork(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	cwd := t.TempDir()
	markJev(t, env, "p1")
	decide := func(p string, a fa) *state.Session {
		t.Helper()
		fj.answers = []fa{a}
		run(t, env, "decide", map[string]any{"session_id": "p1", "prompt": p, "cwd": cwd})
		s, _ := env.State.Load("p1")
		return s
	}
	if s := decide("[effort:max] find the deadlock in the scheduler", fa{tier: "xhigh", conf: 0.9}); s.Main.Tier != "max" || s.Work != nil {
		t.Fatalf("pinned start: %+v, work %+v", s.Main, s.Work)
	}
	s := decide("[effort:auto] ok, and add a test for it", fa{tier: "medium", conf: 0.9, rel: "extend"})
	if s.Main.Tier != "medium" || s.Pin != "" || s.Work == nil || s.Work.Tier != "medium" || fj.last().Questions[jev.QRelation].Type != "" {
		t.Errorf("after [effort:auto]: %+v, work %+v", s.Main, s.Work)
	}
}

// A late decision that keeps the tier still records what it makes of the
// work in progress (a new task at the same level: its goal).
func TestLateDecisionKeepsItsWork(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	var got struct {
		trigger string
		at      time.Time
	}
	spawnLate = func(in *Input, trigger string, at time.Time) { got.trigger, got.at = trigger, at }
	t.Cleanup(func() { spawnLate = func(*Input, string, time.Time) {} })
	env.Cfg.Features.WarmTimeout.Duration = 50 * time.Millisecond
	workSession(t, env, "lw", "xhigh", "", "xhigh")
	in := map[string]any{"session_id": "lw", "prompt": "Next: design how to shard the job queue across regions", "cwd": t.TempDir()}
	fj.delay, fj.answers = 300*time.Millisecond, []fa{{tier: "xhigh", conf: 0.95, rel: "new_task"}}
	run(t, env, "decide", in)
	fj.delay = 0
	t.Setenv(LateEnv, fmt.Sprintf("%s:%d", got.trigger, got.at.UnixNano()))
	run(t, env, "decide", in)
	if s, _ := env.State.Load("lw"); s.Main.Tier != "xhigh" || s.Work.Goal != in["prompt"] {
		t.Errorf("late decision: %+v, work %+v", s.Main, s.Work)
	}
}

// Decisions made without Jev (a fallback, a go-ahead) stay within the
// budget cap and the repo's disable_modes, and drop a mode the capped tier
// can't run.
func TestBoundsWithoutJev(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	cold := func(sid string) {
		env.State.Update(sid, func(s *state.Session) bool { s.ColdHint = true; return true })
	}
	env.Cfg.Budget.USDPerSession = 1
	workSession(t, env, "f1", "xhigh", "ultracode", "xhigh")
	env.State.Update("f1", func(s *state.Session) bool { s.TotalUSD = 5; return true })
	cold("f1")
	fj.fail = true
	run(t, env, "decide", map[string]any{"session_id": "f1", "prompt": "on reprend l'audit", "cwd": t.TempDir()})
	s, _ := env.State.Load("f1")
	if lim := env.Cfg.Budget.MaxTierWhenOver; s.Main.Tier != lim || s.Main.Effort != env.Catalog.Tier(catalog.ScopeMain, lim).Effort || s.Main.Mode != "" || s.Main.Workflows {
		t.Errorf("Jev down over the budget cap: %+v", s.Main)
	}
	env.Cfg.Budget.USDPerSession = 0

	repo := t.TempDir()
	os.WriteFile(filepath.Join(repo, ".automodel.toml"), []byte("disable_modes = [\"ultracode\"]\n"), 0o600)
	os.Mkdir(filepath.Join(repo, ".git"), 0o700)
	workSession(t, env, "f2", "xhigh", "ultracode", "xhigh")
	cold("f2")
	run(t, env, "decide", map[string]any{"session_id": "f2", "prompt": "on reprend l'audit", "cwd": repo})
	if s, _ = env.State.Load("f2"); s.Main.Tier != "xhigh" || s.Main.Mode != "" || s.Main.Workflows {
		t.Errorf("Jev down in a repo without ultracode: %+v", s.Main)
	}
	fj.fail = false
	workSession(t, env, "f3", "low", "", "xhigh")
	env.State.Update("f3", func(s *state.Session) bool { s.Work.Mode = "ultracode"; return true })
	run(t, env, "decide", map[string]any{"session_id": "f3", "prompt": "vas-y", "cwd": repo})
	if s, _ = env.State.Load("f3"); s.Main.Tier != "xhigh" || s.Main.Mode != "" || s.Main.Workflows {
		t.Errorf("go-ahead in a repo without ultracode: %+v", s.Main)
	}
}

// On the model a work asked for in words the decision in force is off the
// tiers: leaving it rebuilds the cache, so a new task Jev is unsure of
// stays on it (at its level); the switch is costed on the model the
// decision ends up on, and a Jev error keeps the decision in force.
func TestLeavingTheWorkModel(t *testing.T) {
	fj := &fakeJev{}
	env := setup(t, fj)
	const sonnet = "claude-sonnet-5-5"
	cwd := t.TempDir()
	decide := func(sid, p string, a fa) (*state.Session, ledger.Decision) {
		t.Helper()
		fj.answers = []fa{a}
		run(t, env, "decide", map[string]any{"session_id": sid, "prompt": p, "cwd": cwd})
		s, _ := env.State.Load(sid)
		all, _ := ledger.Decisions(env.Cfg.Ledger)
		return s, all[len(all)-1]
	}
	onSonnet := func(sid string) {
		t.Helper()
		workSession(t, env, sid, "high", "", "high")
		decide(sid, "passe sur sonnet pour la suite", fa{tier: "high", conf: 0.9, rel: "extend", x: map[string]float64{"model_" + sonnet: 0.95}})
		env.State.Update(sid, func(s *state.Session) bool { s.ContextTokens = 800_000; return true })
	}
	// The gate keeps this turn on Sonnet; the new work goes back to the
	// tiers (a prose model is for the work it was asked for), and its next
	// sure prompt leaves Sonnet.
	onSonnet("o1")
	s, d := decide("o1", "now the same retry logic for the email sender", fa{tier: "medium", conf: 0.3, rel: "new_task", relP: 0.55})
	if s.Main.Model != sonnet || s.Work.Model != "" || s.Work.Goal != "now the same retry logic for the email sender" || !strings.Contains(d.Hold, "confidence 0.30 below 0.80: stays on Sonnet 5.5") {
		t.Errorf("unsure new task: %+v, work %+v, hold %q", s.Main, s.Work, d.Hold)
	}
	if s, _ = decide("o1", "and update the call sites in cmd/ too", fa{tier: "medium", conf: 0.95, rel: "extend"}); s.Main.Model != "claude-opus-5-5" || s.Work.Model != "" {
		t.Errorf("sure follow-up of the new work: %+v, work %+v", s.Main, s.Work)
	}
	onSonnet("o2")
	s, d = decide("o2", "now the same retry logic for the email sender", fa{tier: "medium", conf: 0.9, rel: "new_task"})
	if s.Main.Model != "claude-opus-5-5" || s.Main.Tier != "medium" || d.SwitchUSD <= 1 {
		t.Errorf("sure new task: %+v, switch $%.2f", s.Main, d.SwitchUSD)
	}
	onSonnet("o3")
	fj.fail = true
	s, _ = decide("o3", "now the same retry logic for the email sender", fa{})
	fj.fail = false
	if s.Main.Model != sonnet || s.Main.Effort != "high" {
		t.Errorf("Jev error on the work's model: %+v", s.Main)
	}

	// Going back to paused work that runs on another model costs that
	// model's cache.
	workSession(t, env, "r1", "xhigh", "ultracode", "xhigh")
	env.State.Update("r1", func(s *state.Session) bool { s.Work.Model = sonnet; return true })
	decide("r1", "quick one: fix the typo in the README title", fa{tier: "low", conf: 0.95, rel: "new_task"})
	env.State.Update("r1", func(s *state.Session) bool { s.ContextTokens = 600_000; return true })
	s, d = decide("r1", "ok, back to the pool race", fa{tier: "low", conf: 0.9, rel: "resume", relP: 0.9})
	if s.Main.Model != sonnet || d.SwitchUSD <= 1 {
		t.Errorf("resume onto the paused work's model: %+v, switch $%.2f", s.Main, d.SwitchUSD)
	}
}

// [effort:x] while the work runs on a model the catalog no longer has:
// ignored, not a crash.
func TestWorkModelGoneFromTheCatalog(t *testing.T) {
	fj := &fakeJev{answers: []fa{{tier: "high", conf: 0.9, rel: "extend"}}}
	env := setup(t, fj)
	workSession(t, env, "gm", "high", "", "high")
	env.State.Update("gm", func(s *state.Session) bool {
		s.Work.Model, s.Main.Model, s.Main.Tier = "claude-gone", "claude-gone", state.PinnedTier
		return true
	})
	before, _ := env.State.Load("gm")
	run(t, env, "decide", map[string]any{"session_id": "gm", "prompt": "[effort:high] next part", "cwd": t.TempDir()})
	if s, _ := env.State.Load("gm"); !s.LastPromptAt.After(before.LastPromptAt) || s.Pin != "" {
		t.Errorf("prompt not handled: last prompt %v → %v, pin %q", before.LastPromptAt, s.LastPromptAt, s.Pin)
	}
}
